### ISSUE TITLE
Problem with several expressions with same identifier

### ISSUE THREAD

**Issue by AlbinTheander** [textioHQ/eslint-plugin-banhammer#1]
If there are multiple rules with the same identifier, it will never match any except for the first one. Here is a test you can put among the invalid ones to expose the problem:

```
        {
            code: "two.dontCallMe()",
            options: ["one.dontCallMe","two.dontCallMe"],
            errors: [{
                message: "dontCallMe is not allowed",
                type: "Identifier",
            }],
        },
```

The issue is how you start by finding the identifier and then only run with the first hit you get.

I'll try to put together a pull request with a solution if I have time.

Thanks for a good and useful plugin! :-)

**Comment by AnilRedshift** [comment]
Thanks for the report! I'll look into this and also maybe clean up the code if there are others using the plugin :-)

**Comment by AlbinTheander** [comment]
That would be great.

I checked the code but wasn't really sure how to fix it without a whole bunch of changes. If that's okay with you I would be more than happy to do the work. Just let me know. :-)

**Comment by bkolba** [comment]
Fixed with https://github.com/textioHQ/eslint-plugin-banhammer/issues/2
